### PR TITLE
yara: New App -- Initial release of Yara app

### PR DESCRIPTION
**Pull request by jrm16020**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [X] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [x] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [x] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [x] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [x] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [x] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Initial release of application supports downloading Yara rules with `update yara sources`, listing those files with `list yara sources`, clearing them from disk with `clear yara sources` and scanning with them with `yara scan`.
- `update yara sources` expects an asset with Environment variables defined to be a source for downloading one or more files and a value of the URL to download, something that *requests must support*.
- `list yara sources` will list the application's state directory, by default, and if specified, limit that search to a directory in the app's state directory.  This allows listing sets of malware rules that may all belong to an asset.
- `clear yara sources` will clear all non-state.json files from the app's state directory.
- `yara scan` will compile any downloaded rules, cache them for use later and load any cache before recompiling.  It has boolean parameters for supporting include directives and fast mode.  It allows specifying a scan directory or a vault ID.  Also optionally, specify stack size, max strings per rule, timeout and max match data values to configure how Yara works at runtime.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by achandya-crest** [comment]
Hi @jrm16020, I observed that you are using yara-python module. I added that module in requirements.txt but 4.3.0 version is not being installed. So I am adding yara-python version 4.2.3.

**Comment by jrm16020** [comment]
> .3.

Thank you very much for catching my miss!

**Review by pdesai-crest — APPROVED** [review]

**Comment by achandya-crest** [comment]
Hello @jrm16020, I am changing the min_phantom _version to 5.5.0 as our best practice. Is it fine for you?

**Comment by jrm16020** [comment]
> 

Yes, absolutely!  I'm sorry that I missed this one.

**Review by tonyc-phantom — APPROVED** [review]

**Review by splunk-jessica — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
